### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [FluffyBearYT/1v1System#1]
This plugin crash my server. The console display this message : �[36m[11:33:35] �[m��[36m[Server thread/NOTICE]: UndefinedVariableException: "Undefined variable: event" (E_NOTICE) in "/OnevOne_v1.phar/src/OnevOne/Main" at line 51�[m�

**Comment by KyleTheHack3r** [comment]
https://github.com/FluffyBearYT/1v1System/releases.

**Comment by bulkdev** [comment]
It's not even working, I quit on this because i'm working for PlusPvP now

**Comment by ghost** [comment]
ah ok...
